// <auto-generated />
namespace TacoMovies.Data.Postgre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adjust : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjust));
        
        string IMigrationMetadata.Id
        {
            get { return "201706120819069_adjust"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
