// <auto-generated />
namespace TacoMovies.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeuserfromaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeuserfromaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201706122009554_remove-user-from-account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
