// <auto-generated />
namespace TacoMovies.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class accoutsusersadjustment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accoutsusersadjustment));
        
        string IMigrationMetadata.Id
        {
            get { return "201706120801159_accouts-users-adjustment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
